import { Task, Project, User, Workspace, TaskStatus, Priority, ProjectStatus, Role, ActivityItem, DashboardStats } from "@/types/common";

export const MOCK_CURRENT_USER: User = {
  id: "user-1",
  name: "Sarah Mitchell",
  email: "sarah.mitchell@taskflow.io",
  avatarUrl: "/images/sarah-mitchell.jpg",
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-02-15T00:00:00.000Z",
};

export const MOCK_USERS: User[] = [
  MOCK_CURRENT_USER,
  {
    id: "user-2",
    name: "Alex Rivera",
    email: "alex.rivera@taskflow.io",
    avatarUrl: null,
    createdAt: "2026-01-05T00:00:00.000Z",
    updatedAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "user-3",
    name: "Elena Chen",
    email: "elena.chen@taskflow.io",
    avatarUrl: null,
    createdAt: "2026-01-10T00:00:00.000Z",
    updatedAt: "2026-02-12T00:00:00.000Z",
  },
  {
    id: "user-4",
    name: "David Kim",
    email: "david.kim@taskflow.io",
    avatarUrl: null,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-02-14T00:00:00.000Z",
  },
  {
    id: "user-5",
    name: "Marcus Vance",
    email: "marcus.v@taskflow.io",
    avatarUrl: null,
    createdAt: "2026-01-20T00:00:00.000Z",
    updatedAt: "2026-02-16T00:00:00.000Z",
  },
];

export const MOCK_WORKSPACE: Workspace = {
  id: "ws-alpha",
  name: "Alpha Operations",
  slug: "alpha-operations",
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-02-15T00:00:00.000Z",
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Platform Execution Core",
    description: "High-priority sprint focusing on real-time task sync, edge caching, and mobile responsiveness.",
    status: ProjectStatus.ACTIVE,
    priority: Priority.URGENT,
    startDate: "2026-01-20T00:00:00.000Z",
    dueDate: "2026-02-03T00:00:00.000Z",
    workspaceId: "ws-alpha",
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-02-18T00:00:00.000Z",
    taskCount: 14,
    completedTaskCount: 9,
  },
  {
    id: "proj-2",
    name: "Billing & Stripe Integration",
    description: "Subscription tier management, customer portal, invoices, and webhook reconciliation.",
    status: ProjectStatus.ACTIVE,
    priority: Priority.HIGH,
    startDate: "2026-02-01T00:00:00.000Z",
    dueDate: "2026-02-28T00:00:00.000Z",
    workspaceId: "ws-alpha",
    createdById: "user-2",
    createdBy: MOCK_USERS[1],
    createdAt: "2026-01-25T00:00:00.000Z",
    updatedAt: "2026-02-17T00:00:00.000Z",
    taskCount: 8,
    completedTaskCount: 5,
  },
  {
    id: "proj-3",
    name: "SOC-2 Type II Compliance",
    description: "Audit logging, automated evidence collection, IAM role auditing, and vendor review.",
    status: ProjectStatus.ACTIVE,
    priority: Priority.MEDIUM,
    startDate: "2026-01-10T00:00:00.000Z",
    dueDate: "2026-03-15T00:00:00.000Z",
    workspaceId: "ws-alpha",
    createdById: "user-3",
    createdBy: MOCK_USERS[2],
    createdAt: "2026-01-08T00:00:00.000Z",
    updatedAt: "2026-02-12T00:00:00.000Z",
    taskCount: 12,
    completedTaskCount: 11,
  },
];

export const MOCK_TASKS: Task[] = [
  // TODO / Backlog
  {
    id: "task-101",
    title: "Implement Redis stream worker for bulk notifications",
    description: "Offload email batch dispatching and webhook fan-out from the primary web process to a dedicated background Redis queue.",
    status: TaskStatus.TODO,
    priority: Priority.HIGH,
    dueDate: "2026-02-24T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-2",
    assignee: MOCK_USERS[1],
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [{ id: "l-1", name: "Backend", color: "#4F46E5", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-01T00:00:00.000Z",
    updatedAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "task-102",
    title: "Audit color contrast for accessibility (WCAG AA)",
    description: "Review all text-to-background combinations on dark and light surfaces to pass 4.5:1 ratio requirement.",
    status: TaskStatus.TODO,
    priority: Priority.LOW,
    dueDate: "2026-02-28T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-3",
    assignee: MOCK_USERS[2],
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [{ id: "l-2", name: "Design", color: "#0051d5", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-02T00:00:00.000Z",
    updatedAt: "2026-02-12T00:00:00.000Z",
  },
  {
    id: "task-103",
    title: "Create automated database backup snapshot schedule",
    description: "Configure hourly WAL archiving and daily automated dumps with test restore scripts.",
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    dueDate: "2026-03-02T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-5",
    assignee: MOCK_USERS[4],
    createdById: "user-2",
    createdBy: MOCK_USERS[1],
    labels: [{ id: "l-3", name: "DevOps", color: "#7e3000", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-03T00:00:00.000Z",
    updatedAt: "2026-02-14T00:00:00.000Z",
  },

  // IN_PROGRESS
  {
    id: "task-104",
    title: "Re-architect Kanban drag & drop with optimistic UI updates",
    description: "Ensure cards snap instantly without layout shift and roll back gracefully if network times out.",
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.URGENT,
    dueDate: "2026-02-22T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-1",
    assignee: MOCK_CURRENT_USER,
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [
      { id: "l-4", name: "Frontend", color: "#4F46E5", workspaceId: "ws-alpha" },
      { id: "l-5", name: "UX", color: "#a44100", workspaceId: "ws-alpha" },
    ],
    createdAt: "2026-02-04T00:00:00.000Z",
    updatedAt: "2026-02-18T00:00:00.000Z",
  },
  {
    id: "task-105",
    title: "Implement workspace member role permission guards",
    description: "Add granular CASL / RBAC middleware checking OWNER, ADMIN, and MEMBER permissions on mutation endpoints.",
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    dueDate: "2026-02-23T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-4",
    assignee: MOCK_USERS[3],
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [{ id: "l-1", name: "Backend", color: "#4F46E5", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-05T00:00:00.000Z",
    updatedAt: "2026-02-17T00:00:00.000Z",
  },

  // IN_REVIEW
  {
    id: "task-106",
    title: "Design System: Material 3 Surface elevations",
    description: "Unify container-lowest through container-highest surface hierarchy across all dashboard cards and modals.",
    status: TaskStatus.IN_REVIEW,
    priority: Priority.MEDIUM,
    dueDate: "2026-02-21T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-3",
    assignee: MOCK_USERS[2],
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [{ id: "l-2", name: "Design", color: "#0051d5", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-06T00:00:00.000Z",
    updatedAt: "2026-02-18T00:00:00.000Z",
  },
  {
    id: "task-107",
    title: "Integrate JWT refresh rotation in Edge Middleware",
    description: "Implement silent token renewal using httpOnly cookie exchange before access token expiration window.",
    status: TaskStatus.IN_REVIEW,
    priority: Priority.HIGH,
    dueDate: "2026-02-20T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-2",
    assignee: MOCK_USERS[1],
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [{ id: "l-6", name: "Security", color: "#059669", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-07T00:00:00.000Z",
    updatedAt: "2026-02-18T00:00:00.000Z",
  },

  // DONE
  {
    id: "task-108",
    title: "Next.js 16 App Router setup with Tailwind CSS v4",
    description: "Initial project scaffolding with strict TypeScript typing, path aliases, and baseline design tokens.",
    status: TaskStatus.DONE,
    priority: Priority.HIGH,
    dueDate: "2026-02-15T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-1",
    assignee: MOCK_CURRENT_USER,
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [{ id: "l-4", name: "Frontend", color: "#4F46E5", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-01T00:00:00.000Z",
    updatedAt: "2026-02-15T00:00:00.000Z",
  },
  {
    id: "task-109",
    title: "Public marketing pages (Landing, Pricing, Features, Contact, About)",
    description: "Implement responsive Stitch-faithful marketing pages with rich typography and micro-interactions.",
    status: TaskStatus.DONE,
    priority: Priority.URGENT,
    dueDate: "2026-02-16T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-1",
    assignee: MOCK_CURRENT_USER,
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [{ id: "l-4", name: "Frontend", color: "#4F46E5", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-02T00:00:00.000Z",
    updatedAt: "2026-02-16T00:00:00.000Z",
  },
  {
    id: "task-110",
    title: "Authentication screens (Sign In & Sign Up with demo bypass)",
    description: "Build split-screen auth forms with validation and instant session seeding for review.",
    status: TaskStatus.DONE,
    priority: Priority.HIGH,
    dueDate: "2026-02-17T00:00:00.000Z",
    projectId: "proj-1",
    project: { id: "proj-1", name: "Platform Execution Core" },
    assigneeId: "user-1",
    assignee: MOCK_CURRENT_USER,
    createdById: "user-1",
    createdBy: MOCK_CURRENT_USER,
    labels: [{ id: "l-4", name: "Frontend", color: "#4F46E5", workspaceId: "ws-alpha" }],
    createdAt: "2026-02-03T00:00:00.000Z",
    updatedAt: "2026-02-17T00:00:00.000Z",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "act-1",
    type: "STATUS_CHANGE",
    message: "moved 'Public marketing pages' to Done",
    userId: "user-1",
    user: MOCK_CURRENT_USER,
    createdAt: "10 minutes ago",
  },
  {
    id: "act-2",
    type: "COMMENT",
    message: "commented on 'Audit color contrast': 'Tested with axe-core, AA passes.'",
    userId: "user-3",
    user: MOCK_USERS[2],
    createdAt: "32 minutes ago",
  },
  {
    id: "act-3",
    type: "TASK_CREATED",
    message: "created task 'Implement Redis stream worker'",
    userId: "user-2",
    user: MOCK_USERS[1],
    createdAt: "2 hours ago",
  },
  {
    id: "act-4",
    type: "STATUS_CHANGE",
    message: "submitted PR for 'JWT refresh rotation' for review",
    userId: "user-2",
    user: MOCK_USERS[1],
    createdAt: "4 hours ago",
  },
  {
    id: "act-5",
    type: "MEMBER_JOINED",
    message: "invited David Kim to Alpha Operations as Developer",
    userId: "user-1",
    user: MOCK_CURRENT_USER,
    createdAt: "1 day ago",
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalProjects: 3,
  totalTasks: 23,
  completedTasks: 18,
  pendingTasks: 5,
  totalMembers: 5,
};
